### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DiabloStorm** [NadyaNayme/VoiceOfSeren#1]
For those of us that can't get alt-1 to work, do you have a web-based solution that can show the crowdsourced VOS instead? That would be nice... (Or a FC in game...)

**Comment by NadyaNayme** [comment]
Not currently. I've been trying to get the RS.Wiki involved and several Discord channels (mostly their bots) to bring back role pings for specific hours and to let people check the wiki for the current VoS since we've had data for the large majority of hours within the first few minutes of each hour for a few weeks now. That way people can do a quick `/wiki voice of seren` to check.

When we hit a large enough scale I can make some changes so that visiting https://nadyanayme.github.io/VoiceOfSeren/dist/index.html will work without erroring out if Alt1 isn't found. But if everyone uses that instead of the app the app becomes less reliable so it's a balancing act of being sure enough people are contributing before providing an easier avenue to not contribute but still benefit.

**Comment by keikepono** [comment]
I've created a bot with a few commands and have quickly written something to incorporate this into my bot. I could add a message to the bot to encourage users to download your alt1 extension to enable better crowd sourcing. Are you on board with that idea?

**Comment by NadyaNayme** [comment]
If you're making use of the API - yes - please encourage users to actually install/use the plugin as well. While we absolutely want people to be able to benefit from it via Discord bots - it does mean an increase in leechers and a potential decline of contributors which makes the app less reliable for everyone. 

I still make an effort to update the VoS when it isn't a total inconvenience for me but since I refuse to add analytics I'm not sure how many other contributors there are currently.

**Comment by n-jones0** [comment]
Base Alt 1 has a D&D notification that can be viewed without the app [here](https://runeapps.org/notifications). Would you be willing to work with them to try to get the crowdsourced VoS integrated into it? (One of its strengths is being able to display the current VoS directly in the titlebar)

**Comment by NadyaNayme** [comment]
> Base Alt 1 has a D&D notification that can be viewed without the app [here](https://runeapps.org/notifications). Would you be willing to work with them to try to get the crowdsourced VoS integrated into it? (One of its strengths is being able to display the current VoS directly in the titlebar)

Statusdaemon support is being purposefully left out. Apps are capable of updating the titlebar when closed - but due to how data is gathered requires the app to be open forcing people to either choose between opening+closing the app constantly or just minifying it and leaving it open is an intentional decision meant to increase the number of contributors. If you leave the app open the current VoS will display directly in the titlebar. It's only if you close the app that it will stop receiving updates.

Skillbert is always free to consume the crowdsourced API for the D&D notifications app if he so wishes but I think the unreliability of it not coming from Jagex makes him a bit adverse to it as anytime it is wrong people would bug him instead of bugging me about it when he has no control over things.
